# Generated by Django 5.2.5 on 2025-08-08 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='CPF')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('wage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Contratação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima Alteração')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Data de Saída')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
